# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieDBApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDBApp

pod 'RxSwift', '6.2.0'
pod 'RxCocoa', '6.2.0'
pod 'Alamofire', '~> 5.4'
pod 'ObjectMapper', '~> 3.5'
pod 'SDWebImage', '~> 5.0'
pod 'Reusable'
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'NSObject+Rx'

end
